### ISSUE TITLE
Zabbix url path

### ISSUE THREAD

**Issue by ranzpirat** [openbaton/zabbix-plugin#10]
Currently the zabbix-plugin demands that the zabbix-server installation is reachable with `http://ip/zabbix` path set. This is not the case when deploying e.g. with the official zabbix docker-containers.

See https://github.com/openbaton/zabbix-plugin/blob/master/src/main/java/org/openbaton/monitoring/agent/ZabbixSender.java#L54

Maybe introduce a way to override the path and only fallback to the default (/zabbix path is suggested by official zabbix documentation) when not set.

**Comment by marcellom** [comment]
Fixed with https://github.com/openbaton/zabbix-plugin/pull/11
